site_name: Android Interview
theme:
    name: mkdocs
    custom_dir: 'my_material'
    language: zh
    palette:
    primary: indigo
    accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    logo:
      icon: "\uE80C"
    feature:
      tabs: true